'use strict';

angular.module('sondageApp')
    .service('coursService', function () {
        //[sigle, titre, false, hasLabs]
        this.cours = [
            ["ELE1300", "Circuits logiques", false, true],
            ["ELE1001", "Travail en équipe et projet", false, true],
            ["ELE1600A", "Circuits électriques", false, true],
            ["ELE2305", "Dispositifs à semi-conducteurs et optoélectronique", false, true],
            ["ELE2611", "Circuits actifs", false, true],
            ["ELE2000", "Projets de circuits électroniques", false, true],
            ["ELE2700", "Analyse des signaux", false, true],
            ["ELE2200", "Systèmes et simulation", false, true],
            ["ELE2310", "Électronique", false, true],
            ["ELE2400", "Électricité: sécurité et environnement", false, true],
            ["ELE3312", "Microcontrôleurs et applications", false, true],
            ["ELE3500", "Ondes électromagnétiques", false, true],
            ["ELE3400", "Électrotechnique", false, true],
            ["ELE3701A", "Éléments de télécommunication", false, true],
            ["ELE3201", "Asservissements", false, true],
            ["ELE3311", "Systèmes logiques programmables", false, true],
            ["ELE3000", "Projet personnel en génie électrique", false, true],
            ["ELE3705", "Transmission de l'information", false, true],
            ["MTH1101", "Calcul I", false, false],
            ["MTH1006", "Algèbre linéaire", false, false],
            ["INF1005C", "Programmation procédurale", false, true],
            ["MTH1102", "Calcul II", false, false],
            ["MTH1115", "Équations différentielles", false, false],
            ["PHS1102", "Champs électromagnétiques", false, true],
            ["PHS1101", "Mécanique pour ingénieurs", false, false],
            ["MTH2120", "Analyse appliquée", false, false],
            ["MTH2210A", "Calcul scientif. pour ing.", false, false],
            ["INF1010", "Programmation orientée objet", false, true],
            ["PHS1104", "Thermodynamique et transfert de chaleur", false, false],
            ["SSH5501", "Éthique appliquée à l'ingénierie", false, false],
            ["IND2301", "Gestion de projets technologiques", false, false],
            ["ING4901", "Projet intégr. dév. durable", false, false],
            ["SSH5201", "Économique de l'ingénieur", false, true],
            ["SSH5100", "Sociologie de la technologie", false, false],
            ["ELE4200", "Introduction à la commande par ordinateur", false, true],
            ["ELE4202", "Commande des processus industriels", false, true],
            ["ELE4203", "Robotique", false, true],
            ["AER4410", "Commande de vol et de moteurs", false, true],
            ["ELE4300A", "Électronique analogique", false, true],
            ["ELE4451", "Dispositifs d'électronique de puissance", false, true],
            ["ELE4455", "Systèmes électromécaniques", false, true],
            ["ELE8812", "Traitement et analyse d'images", false, true],
            ["GBM3000", "Physiologie, systèmes et technologies", false, false],
            ["GBM3103", "Réglementation des instruments médicaux", false, false],
            ["GBM3318", "Principes d'imagerie biomédicale", false, true],
            ["GBM3810", "Biomicrosystèmes", false, true],
            ["GBM8320", "Dispositifs médicaux intelligents", false, true],
            ["ELE4458", "Électricité industrielle", false, true],
            ["ELE6411A", "Étude des grands réseaux électriques", false, false],
            ["ELE8401", "Machines et entraînements électriques", false, false],
            ["ELE8459", "Protection des réseaux", false, true],
            ["ELE4306", "vÉlectronique des communications", false, true],
            ["ELE8304", "Circuits intégrés à très grande échelle", false, true],
            ["ELE8307", "Prototypage rapide de systèmes numériques", false, true],
            ["TS3100", "Introduction aux systèmes spatiaux", false, false],
            ["TS4500", "Introduction aux antennes de satellites", false, true],
            ["ELE4501A", "Circuits et systèmes comm. radiofréquences", false, true],
            ["ELE8702", "Réseaux de communication sans fil", false, true],
            ["PHS8501", "Bases physiques de la télédétection", false, false],
            ["ELE4500", "Circuits passifs micro-ondes", false, true],
            ["ELE4700A", "Transmission numérique", false, true],
            ["ELE8704", "Transmission de données et réseaux internet", false, true],
            ["ELE8705", "Télécommunications mobiles", false, true],
            ["DDI8001", "Développement durable pour ingénieurs", false, false],
            ["DDI8002", "Études de cas en dévelop. durable pour ing.", false, false],
            ["CIV4750", "Planification durable des transports", false, true],
            ["ENE8210", "Efficacité des sources d'énergie", false, true],
            ["MEC4230", "Combustion et pollution atmosphérique", false, false],
            ["MEC4250", "Design et efficacité énergétique en méc. bât.", false, false],
            ["SSH5402", "Droit de l'environnement", false, false],
            ["4-084-13", "Développement durable, politiques environnementales et gestion (HEC)", false, false],
            ["4-801-06", "Analyse économique des enjeux environnementaux (HEC)", false, false],
            ["EDD6050", "Gestion de la biodiversité", false, false],
            ["GEO6295", "Territoires et développement durable", false, false],
            ["MSN6115", "Santé et environnement", false, false],
            ["IND4710", "Gestion de la R-D et de l'innovation", false, false],
            ["IND4711", "Innovation technologique et industrielle", false, false],
            ["IND8137A", "Entrepreneuriat technologique", false, false],
            ["IND6110A", "Stratégies technologiques", false, false],
            ["IND8120", "Commercialisat. nouveaux produits et services", false, false],
            ["IND8144", "Financement de l'entreprise technologique", false, false],
            ["MTH8207", "Mathématiques des éléments finis", false, false],
            ["MTH8515", "Analyse mathématique avancée pour ingénieurs", false, false],
            ["MTH8301", "Planification et analyse stat. d'expériences", false, false],
            ["MTH8302", "Analyse de régression et analyse de variance", false, false],
            ["MTH8303", "Processus stochastiques", false, false],
            ["MTH8408", "Méthodes d'optimisation et contrôle optimal", false, false],
            ["MTH8414", "Outils de recherche opérationnelle en génie", false, false],
            ["MTH8442", "Ordonnancement de la production", false, false],
            ["MTH3400", "Analyse mathématique pour ingénieurs", false, false],
            ["IND5200", "Organisation industrielle", false, true],
            ["IND8211", "Ingénierie des systèmes d'information", false, false],
            ["IND5501", "Droit du travail pour ingénieur", false, false],
            ["IND8107", "Gestion des changements technol. et organis.", false, false],
            ["IND8119", "Gestion d'équipes dans un environnement tech.", false, false],
            ["IND4704", "Théorie de la décision", false, false],
            ["IND5115", "Technologie et concurrence internationale", false, false],
            ["IND8127A", "Mondialisation et firmes internationales", false, false],
            ["IND8138", "Gestion de projets internationaux", false, false],
            ["IND5120", "Ingénieur en coop. et dévelop. international", false, false],
            ["IND5116", "Mission industrielle: Poly-Monde", false, false],
            ["ELE4452", "Réseaux électriques", false, true],
            ["ELE4000", "Projet intégrateur de grande envergure", false, false],
            ["ING4901", "Projet intégrateur en développement durable", false, false],
            ["ELE8456", "Réseaux de distribution", false, true],
            ["ELE8457", "Comportement des réseaux électriques", false, true],
            ["ELE8460", "Appareillage électrique", false, true],
            ["PHS8310", "Microfabrication", false, true],
            ["ELE8508", "Concepts fondamentaux de photonique", false, true],
            ["INF2610", "Noyau d'un système d'exploitation", false, true],
            ["INF8505", "Processeurs embarqués configurables", false, true],
            ["PHS8311", "Microsystèmes", false, false],
            ["SPL4710", "Perception et cognition en robotique", false, false],
            ["SPL4720", "Système et interface en robotique", false, false],
            ["SPL4730", "Signaux et images en robotique", false, false],
            ["SPL4740", "Séminaire", false, false],
            ["SPL4750", "Application des systèmes interactifs et robotiques", false, false],
            ["AER4200", "Conception des systèmes électriques d'avion", false, true],
            ["AER4400", "Archit. et certif. des systèmes d'aéronefs", false, false],
            ["AER4715", "Avionique", false, true],
            ["AER4720", "Intégration des systèmes avioniques", false, false],
            ["AER8500", "Informatique embarquée de l'avionique", false, true],
            ["AER4900", "Projet intégr. en syst. emb. en aérospatial", false, false],
            ["AER3205", "Caractéristiques de l'avion", false, true],
            ["SPL4420", "Économie et géopolitique de l'énergie", false, false],
            ["SPL4440", "Étude industrielle", false, false],
            ["SPL4450", "Énergie et application", false, false],
            ["SPL4460", "Langue vivante", false, false],
            ["SPL4430", "Systèmes électriques", false, false],
            ["SPL4480", "Réseaux d'énergie", false, false],
            ["SPL4410", "Sources et production d'énergie", false, false],
            ["MTH2302A", "Probabilités et statistique", false, false]
        ];

        this.getCours = function () {
            return this.cours;
        };
    });